### ISSUE TITLE
Could not run the go binary

### ISSUE THREAD

**Issue by syntaxwanderer** [canthefason/go-watcher#20]
taras@taras-Z370-HD3P /media/taras/Storage/source/server-panel $ watcher
2018/02/10 17:52:26 build started
Building ....
2018/02/10 17:52:27 build completed
Running ...
2018/02/10 17:52:27 Could not run the go binary: exec: "-.-533426": executable file not found in $PATH 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4718b8]

goroutine 7 [running]:
os.(*Process).signal(0x0, 0x573800, 0x5720e8, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:56 +0x38
os.(*Process).Signal(0x0, 0x573800, 0x5720e8, 0x54, 0xc420082180)
	/usr/local/go/src/os/exec.go:121 +0x3f
os.(*Process).kill(0x0, 0xc4200840f0, 0x2)
	/usr/local/go/src/os/exec_posix.go:53 +0x43
os.(*Process).Kill(0x0, 0x0, 0x54)
	/usr/local/go/src/os/exec.go:106 +0x2b
github.com/canthefason/go-watcher.(*Runner).kill(0xc42000a500, 0xc42014e160)
	/home/taras/go/src/github.com/canthefason/go-watcher/run.go:66 +0x41
github.com/canthefason/go-watcher.(*Runner).Run(0xc42000a500, 0xc42000a080)
	/home/taras/go/src/github.com/canthefason/go-watcher/run.go:39 +0x23c
created by main.main
	/home/taras/go/src/github.com/canthefason/go-watcher/cmd/watcher/main.go:17 +0x120

**Comment by thinkjson** [comment]
Same.

**Comment by canthefason** [comment]
go-watcher should be run with the same level of your main package. But I would appreciate if you can elaborate on your use case a bit.

**Comment by thinkjson** [comment]
I had a single source file, main.go, and was trying to use watcher to autocompile on change.

**Comment by silencej** [comment]
Me too. Mine: "go version go1.11.4 darwin/amd64"

**Comment by keiqiu** [comment]
just set GOPATH 
ex: export GOPATH=/root/go
